format = """
$directory\
${custom.git_indicator}  \
$git_branch\
$git_status\
$line_break\
$character"""

add_newline = true
palette = 'nord'

[directory]
style = 'bold fg:dark_blue'
format = '[$path ]($style)'
truncate_to_repo = false

[directory.substitutions]
'Documents' = '󰈙'
'Downloads' = ' '
'Music' = ' '
'Pictures' = ' '

[custom.git_indicator]
when = 'git rev-parse --is-inside-work-tree 2>/dev/null'
command = 'echo ""'
format = '[$output]($style)'
style = 'bold fg:purple'

[git_branch]
style = 'fg:purple'
always_show_remote = true
symbol = ' '
format = '[$symbol$branch(:$remote_branch)]($style)'

[git_status]
style = 'fg:purple'
format = ' [\($all_status$ahead_behind\)]($style)'
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
up_to_date = '✓'

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

[palettes.nord]
dark_blue = '#5E81AC'
blue = '#81A1C1'
teal = '#88C0D0'
orange = '#D08770'
green = '#A3BE8C'
yellow = '#EBCB8B'
purple = '#B48EAD'
gray = '#434C5E'
black = '#2E3440'
white='#D8DEE9'
