# Prefix Key
set -g prefix C-s
unbind C-b

# Enable mouse support
set -g mouse on

# Reload configuration
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"

# Pane Splitting
unbind %
unbind '"'
bind | split-window -h
bind - split-window -v

# Pane Resizing
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Smart pane switching with awareness of Vim splits.
# See: https://github.com/christoomey/vim-tmux-navigator
vim_pattern='(\S+/)?g?\.?(view|l?n?vim?x?|fzf)(diff)?(-wrapped)?'
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +${vim_pattern}$'"
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'
tmux_version='$(tmux -V | sed -En "s/^tmux ([0-9]+(.[0-9]+)?).*/\1/p")'
if-shell -b '[ "$(echo "$tmux_version < 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\'  'select-pane -l'"
if-shell -b '[ "$(echo "$tmux_version >= 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\\\'  'select-pane -l'"

bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key -T copy-mode-vi 'C-\' select-pane -l

# --- Gruvbox palette ---
set -g @gb_bg       "#282828"
set -g @gb_bg0_s     "#32302f"
set -g @gb_bg0_h    "#1d2021"
set -g @gb_bg1      "#3c3836"
set -g @gb_bg2      "#504945"
set -g @gb_fg       "#ebdbb2"
set -g @gb_gray     "#928374"

set -g @gb_red      "#cc241d"
set -g @gb_green    "#98971a"
set -g @gb_yellow   "#d79921"
set -g @gb_blue     "#458588"
set -g @gb_purple   "#b16286"
set -g @gb_aqua     "#689d6a"
set -g @gb_orange   "#d65d0e"

set -g @half_round_open   ""
set -g @half_round_close  ""

# --- Status bar ---
set -g status "on"
set -g status-style "bg=#{@gb_bg0_s},fg=#{@gb_fg}"
set -g status-justify centre

set -g status-left "\
#[fg=#{@gb_bg2},bg=#{@gb_bg0_s}]#{@half_round_open}\
#[bg=#{@gb_bg2},fg=#{@gb_aqua},bold] #S \
"

set -g status-right "\
#[bg=#{@gb_bg2},fg=#{@gb_aqua}] #h \
#[fg=#{@gb_bg2},bg=#{@gb_bg0_s}]#{@half_round_close}\
"

set -g window-status-format "\
#[fg=#{@gb_bg2},bg=#{@gb_bg0_s}]#{@half_round_open}\
#[fg=#{@gb_gray}] #I:#W \
#[fg=#{@gb_bg2},bg=#{@gb_bg0_s}]#{@half_round_close}\
"
set -g window-status-current-format "\
#[fg=#{@gb_bg2},bg=#{@gb_bg0_s}]#{@half_round_open}\
#[bg=#{@gb_bg2},fg=#{@gb_purple},bold] #I:#W \
#[fg=#{@gb_bg2},bg=#{@gb_bg0_s}]#{@half_round_close}\
"

# Pane border
set -g pane-border-style "fg=#{@gb_bg1}"
set -g pane-active-border-style "fg=#{@gb_bg2}"

# Message style
set -g message-style "bg=#{@gb_bg1},fg=#{@gb_fg}"
